dialogos_tutorial = {'dialogo1': CaixaDialogo(['Não se preocupem, tenho certeza que os escolhidos irão',
                                                       'facilmente aprender as técnicas que ensinarei.'],
                                                      self.bethoven),
                             'dialogo2': CaixaDialogo(['Para se mexer para os lados, aperte (esquerda, direita)',
                                                       'Para pular, aperte (cima).'], self.bethoven),
                             'dialogo3': CaixaDialogo(['Você está no modo violão, uma arma musical versátil e ',
                                                       'razoavelmente poderosa. Aperte (z) para atirar com ela.'],
                                                      self.bethoven),
                             'dialogo4': CaixaDialogo(['Ótimo!'], self.bethoven),
                             'dialogo5': CaixaDialogo(['Os tiros sairão na direção que você estiver olhando. ',
                                                       'Você também pode apertar ou (baixo) para atirar ',
                                                       'para para baixo. Tente agora.'], self.bethoven),
                             'dialogo6': CaixaDialogo(['Ótimo!'], self.bethoven),
                             'dialogo7': CaixaDialogo(['Durante o modo violão, você tem a habilidade de posicionar ',
                                                       'uma caixa de som apertando X. Aperte (X).'], self.bethoven),
                             'dialogo8': CaixaDialogo(['Muito bem!',
                                                       'Ela dura 6 segundos, e enquanto estiver viva, todos os tiros do',
                                                       'violão sairão por ela.'], self.bethoven),
                             'dialogo9': CaixaDialogo(['A caixa de som pode ser muito útil ou não em algumas situações.'
                                                       'Porém, a depender da situação, se preferir, pode apertar X de'
                                                       'novo para fazê-la desaparecer.'], self.bethoven),
                             'dialogo10': CaixaDialogo(['Os escolhidos têm uma barra de mana.',
                                                        'Com o tempo, ela recarrega.'], self.bethoven),
                             'dialogo11': CaixaDialogo(['Quando a barra de mana estiver cheia, você pode apertar (C) ',
                                                        'para ativar o especial do piano. Aperte (C)'], self.bethoven),
                             'dialogo12': CaixaDialogo(['Enquanto estiver no modo pianista, você estará invulnerável.',
                                                        'Ao apertar (Z) ou segurar, você invoca e atira com seu piano'],
                                                       self.bethoven),
                             'dialogo13': CaixaDialogo(['O modo piano dura um máximo de 3 segundos, mas você pode sair'
                                                        'antes apertando C de novo.'], self.bethoven),
                             'dialogo14': CaixaDialogo(['Vocês estão prontos! Vão!',
                                                        'Restaurem a música!!'], self.bethoven)